# Generated by Django 3.2.8 on 2022-01-09 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoulPlace', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
