# Generated by Django 3.2.8 on 2022-01-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoulPlace', '0003_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='suggestion',
            new_name='suggestion_p',
        ),
    ]
